name: Build

on: 
  push:
    branches: [main]


jobs:
  backend-aarch64:
    name: Backend linux aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          working-directory: ./thirtyone-backend
          command: build
          args: --target aarch64-unknown-linux-gnu
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: thirtyone-frontend/package-lock.json
      - run: npm install
        working-directory: ./thirtyone-frontend
      - run: npm build
        working-directory: ./thirtyone-frontend
