name: Build

on: 
  push:
    branches: [main]

jobs:
  backend-aarch64:
    name: Backend linux aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cross
        run: cargo install cross
      - name: Build
        working-directory: ./thirtyone-backend
        run: cross build --target aarch64-unknown-linux-gnu
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
        working-directory: ./thirtyone-frontend
      - run: npm run build
        working-directory: ./thirtyone-frontend
